#!/usr/bin/env python3
# =============================================================================
# gen_data_diagrams.py  -  WhiskyBase data-driven diagram generator
# =============================================================================
# Emits the STRICT-register technical graphs for the educational concept
# pages: precise, no hand-drawn wobble filter, real axes and data.
# Per docs/diagram-style.md: hardware schematics are hand-drawn sketches;
# data graphs are strict. Every data graph carries a described label on
# every axis (quantity + unit), tick labels, and a full grid (horizontal
# and vertical).
#
# Sources reproduced:
#   data/diagrams/spirit-cut.svg               <- Miller (2024) Fig. 6.7
#   data/diagrams/cask-maturation-kinetics.svg <- Miller (2024) Fig. 8.11
# Re-run after any data change:  python3 scripts/gen_data_diagrams.py
# =============================================================================
import os

DIAG = os.path.normpath(os.path.join(os.path.dirname(__file__), '..', 'data', 'diagrams'))


def plot(xv, x0, x1, L, R):
    return L + (xv - x0) / (x1 - x0) * (R - L)


def yplot(yv, y0, y1, T, B):
    return B - (yv - y0) / (y1 - y0) * (B - T)


def grid(L, R, T, B, xticks, yticks, px, py):
    """Full grid: horizontal line at every y tick, vertical at every x tick."""
    out = ['  <g stroke="var(--muted-color)" stroke-width="1" opacity="0.32">']
    for yv in yticks:
        yy = py(yv)
        out.append(f'    <line x1="{L}" y1="{yy:.1f}" x2="{R}" y2="{yy:.1f}"/>')
    for xv in xticks:
        xx = px(xv)
        out.append(f'    <line x1="{xx:.1f}" y1="{T}" x2="{xx:.1f}" y2="{B}"/>')
    out.append('  </g>')
    return out


def axes(L, R, T, B, xticks, yticks, px, py):
    out = ['  <g stroke="currentColor" stroke-width="1.7" fill="none" '
           'stroke-linecap="round">',
           f'    <line x1="{L}" y1="{T}" x2="{L}" y2="{B}"/>',
           f'    <line x1="{L}" y1="{B}" x2="{R}" y2="{B}"/>']
    for xv in xticks:
        xx = px(xv)
        out.append(f'    <line x1="{xx:.1f}" y1="{B}" x2="{xx:.1f}" y2="{B+6}"/>')
    for yv in yticks:
        yy = py(yv)
        out.append(f'    <line x1="{L-6}" y1="{yy:.1f}" x2="{L}" y2="{yy:.1f}"/>')
    out.append('  </g>')
    return out


# -----------------------------------------------------------------------------
# 1. spirit-cut.svg  -  DMTS through the spirit-still run (Miller Fig. 6.7)
# -----------------------------------------------------------------------------
def spirit_cut():
    L, R, T, B = 116, 712, 74, 362
    x0, x1, y0, y1 = 0, 100, 0, 180
    px = lambda v: plot(v, x0, x1, L, R)
    py = lambda v: yplot(v, y0, y1, T, B)
    xticks = list(range(0, 101, 10))
    yticks = list(range(0, 181, 20))
    curve = [(0, 38), (2, 120), (4, 165), (6, 152), (8, 128), (10, 110),
             (12, 96), (15, 78), (20, 58), (25, 45), (30, 34), (35, 27),
             (40, 20), (44, 13), (48, 12), (52, 9), (56, 5), (60, 2),
             (66, 1), (75, 0.5), (85, 0.2), (100, 0)]
    e = ['<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 768 470" '
         'role="img" aria-labelledby="sc-t sc-d" class="wb-diagram wb-chart">',
         '  <!-- WhiskyBase data diagram (STRICT register, generated by '
         'scripts/gen_data_diagrams.py). Reproduces Miller, Whisky Science '
         '2nd ed. 2024, Fig. 6.7. No sketch filter: technical graphs are '
         'drawn precisely, with described axes, tick labels and a full grid. -->',
         '  <title id="sc-t">DMTS through the spirit-still run</title>',
         '  <desc id="sc-d">Graph reproducing Miller Fig. 6.7: the '
         'concentration of dimethyl trisulphide in the condensate is highest '
         'in the foreshots and the start of the run, then falls steeply. The '
         'horizontal axis is the total volume collected as a percentage; the '
         'vertical axis is DMTS concentration in micrograms per litre. The '
         'shaded band marks the usual head-cut range.</desc>']
    e += grid(L, R, T, B, xticks, yticks, px, py)
    bx1, bx2 = px(10), px(20)
    e.append(f'  <rect x="{bx1:.1f}" y="{T}" width="{bx2-bx1:.1f}" '
             f'height="{B-T}" fill="var(--muted-color)" opacity="0.13"/>')
    e.append('  <g stroke="var(--muted-color)" stroke-width="1.3" '
             'stroke-dasharray="5 4">')
    e.append(f'    <line x1="{bx1:.1f}" y1="{T}" x2="{bx1:.1f}" y2="{B}"/>')
    e.append(f'    <line x1="{bx2:.1f}" y1="{T}" x2="{bx2:.1f}" y2="{B}"/>')
    e.append('  </g>')
    e += axes(L, R, T, B, xticks, yticks, px, py)
    d = 'M ' + ' L '.join(f'{px(x):.1f} {py(y):.1f}' for x, y in curve)
    e.append(f'  <path d="{d}" fill="none" stroke="currentColor" '
             f'stroke-width="2.6" stroke-linejoin="round" stroke-linecap="round"/>')
    e.append('  <g fill="var(--muted-color)" font-size="12" stroke="none">')
    for xv in xticks:
        e.append(f'    <text x="{px(xv):.1f}" y="{B+22}" '
                 f'text-anchor="middle">{xv}</text>')
    for yv in yticks:
        e.append(f'    <text x="{L-12}" y="{py(yv)+4:.1f}" '
                 f'text-anchor="end">{yv}</text>')
    e.append('  </g>')
    e.append('  <g fill="var(--text-color)" font-size="13.5" stroke="none">')
    e.append(f'    <text x="{(L+R)/2:.0f}" y="{B+46}" text-anchor="middle">'
             f'Total volume of foreshots + spirit collected [%]</text>')
    e.append(f'    <text transform="rotate(-90 34 {(T+B)/2:.0f})" x="34" '
             f'y="{(T+B)/2:.0f}" text-anchor="middle">'
             f'DMTS in condensate [µg/L]</text>')
    e.append('  </g>')
    bxc = (bx1 + bx2) / 2
    e.append('  <g fill="var(--muted-color)" stroke="none">')
    e.append(f'    <text x="{bxc:.0f}" y="{T+20}" font-size="12.5" '
             f'text-anchor="middle">head-cut range</text>')
    e.append(f'    <text x="{L}" y="458" font-size="11">Reproduced from '
             f'Miller, Whisky Science (2nd ed., 2024), Fig. 6.7.</text>')
    e.append('  </g>')
    e.append('</svg>')
    return '\n'.join(e) + '\n'


# -----------------------------------------------------------------------------
# 2. cask-maturation-kinetics.svg  -  dissolved solids vs age (Miller Fig. 8.11)
# -----------------------------------------------------------------------------
def cask_maturation():
    L, R, T, B = 130, 716, 60, 386
    x0, x1, y0, y1 = 0, 96, 0, 300
    px = lambda v: plot(v, x0, x1, L, R)
    py = lambda v: yplot(v, y0, y1, T, B)
    xticks = list(range(0, 97, 12))
    yticks = list(range(0, 301, 50))
    pts = [(0, 8, 7), (3, 44, 27), (6, 88, 35), (12, 111, 35), (18, 128, 36),
           (24, 136, 37), (30, 146, 38), (36, 155, 39), (42, 158, 41),
           (48, 166, 41), (54, 166, 40), (60, 173, 45), (66, 174, 43),
           (72, 184, 42), (78, 183, 49), (84, 202, 56), (90, 202, 47),
           (96, 207, 42)]
    e = ['<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 772 470" '
         'role="img" aria-labelledby="cm-t cm-d" class="wb-diagram wb-chart">',
         '  <!-- WhiskyBase data diagram (STRICT register, generated by '
         'scripts/gen_data_diagrams.py). Reproduces Miller, Whisky Science '
         '2nd ed. 2024, Fig. 8.11 (dissolved solids, 469 charred casks). '
         'Means with plus/minus 2 sigma error bars; described axes, tick '
         'labels and a full grid. -->',
         '  <title id="cm-t">Dissolved solids through cask maturation</title>',
         '  <desc id="cm-d">Graph reproducing Miller Fig. 8.11: dissolved '
         'solids extracted into the spirit rise rapidly in the first year and '
         'slowly thereafter. The horizontal axis is cask age in months; the '
         'vertical axis is dissolved solids in grams per 100 litres. Points '
         'are means of 469 charred casks; error bars show plus or minus two '
         'standard deviations.</desc>']
    e += grid(L, R, T, B, xticks, yticks, px, py)
    e += axes(L, R, T, B, xticks, yticks, px, py)
    e.append('  <g stroke="currentColor" stroke-width="1.6" '
             'stroke-linecap="round">')
    for age, m, err in pts:
        cx = px(age)
        ytop, ybot = py(m + err), py(m - err)
        e.append(f'    <line x1="{cx:.1f}" y1="{ytop:.1f}" '
                 f'x2="{cx:.1f}" y2="{ybot:.1f}"/>')
        e.append(f'    <line x1="{cx-4:.1f}" y1="{ytop:.1f}" '
                 f'x2="{cx+4:.1f}" y2="{ytop:.1f}"/>')
        e.append(f'    <line x1="{cx-4:.1f}" y1="{ybot:.1f}" '
                 f'x2="{cx+4:.1f}" y2="{ybot:.1f}"/>')
    e.append('  </g>')
    e.append('  <g fill="currentColor" stroke="none">')
    for age, m, err in pts:
        e.append(f'    <circle cx="{px(age):.1f}" cy="{py(m):.1f}" r="4.2"/>')
    e.append('  </g>')
    e.append('  <g fill="var(--muted-color)" font-size="12" stroke="none">')
    for xv in xticks:
        e.append(f'    <text x="{px(xv):.1f}" y="{B+22}" '
                 f'text-anchor="middle">{xv}</text>')
    for yv in yticks:
        e.append(f'    <text x="{L-12}" y="{py(yv)+4:.1f}" '
                 f'text-anchor="end">{yv}</text>')
    e.append('  </g>')
    e.append('  <g fill="var(--text-color)" font-size="13.5" stroke="none">')
    e.append(f'    <text x="{(L+R)/2:.0f}" y="{B+46}" text-anchor="middle">'
             f'Cask age [months]</text>')
    e.append(f'    <text transform="rotate(-90 34 {(T+B)/2:.0f})" x="34" '
             f'y="{(T+B)/2:.0f}" text-anchor="middle">'
             f'Dissolved solids [g per 100 L]</text>')
    e.append('  </g>')
    e.append('  <g fill="var(--muted-color)" stroke="none" font-size="11">')
    e.append(f'    <text x="{L}" y="458">Reproduced from Miller, Whisky '
             f'Science (2nd ed., 2024), Fig. 8.11 — means of 469 charred '
             f'casks, error bars ±2σ.</text>')
    e.append('  </g>')
    e.append('</svg>')
    return '\n'.join(e) + '\n'


def main():
    for name, fn in [('spirit-cut.svg', spirit_cut),
                      ('cask-maturation-kinetics.svg', cask_maturation)]:
        path = os.path.join(DIAG, name)
        with open(path, 'w', encoding='utf-8', newline='\n') as fh:
            fh.write(fn())
        print(f'wrote {path}  ({os.path.getsize(path)} bytes)')


if __name__ == '__main__':
    main()
